# SPDX-License-Identifier: GPL-2.0

mtk-isp-p1-camsv-objs += mtk_camsv.o
mtk-isp-p1-camsv-objs += mtk_camsv_hw.o
mtk-isp-p1-camsv-objs += mtk_camsv_video.o

obj-$(CONFIG_MTK_ISP_P1_CAMSV) += mtk-isp-p1-camsv.o
