# SPDX-License-Identifier: GPL-2.0

mtk-camsv-objs += mtk_camsv.o
mtk-camsv-objs += mtk_camsv_hw.o
mtk-camsv-objs += mtk_camsv_video.o

obj-$(CONFIG_MTK_CAMSV) += mtk-camsv.o

mtk-isp20-cam-objs += mtk_camsv.o
mtk-isp20-cam-objs += mtk_camctl_hw.o
mtk-isp20-cam-objs += mtk_camsv_video.o

obj-$(CONFIG_MTK_ISP_20) += mtk-isp20-cam.o

mtk-camsv30-objs += mtk_camsv.o
mtk-camsv30-objs += mtk_camsv30_hw.o
mtk-camsv30-objs += mtk_camsv_video.o

obj-$(CONFIG_MTK_CAMSV30) += mtk-camsv30.o
